name: pagebreakfast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  interval_ticker_provider: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bananna.png

  fonts:
    - family: rubik scribble
      fonts:
        - asset: fonts/Rubik_Scribble/RubikScribble-Regular.ttf

    - family: acme
      fonts:
        - asset: fonts/Acme/Acme-Regular.ttf
